dubbo:
  scan:
    base-packages: com.haochang.boot.impl
  protocols:
    dubbo:
      name: dubbo
      port: -1
    rest:
      name: rest
      port: 8888
      server: netty
  registry:
    address: spring-cloud://localhost

spring:
  application:
    name: dubbo-rest-provider
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  main:
    allow-bean-definition-overriding: true