spring:
  application:
    name: dubbo-rest-provider
dubbo:
  protocol:
    name: dubbo
    serialization: kryo
    port: 20980
  registry:
    address: nacos://10.108.2.126:8848 # 自己的nacos地址
    check: false
    group: noncore
    version: 1.0
    protocol: nacos
    parameters:
      namespace: dev
  provider:
    version: 1.0
    group: noncore