
spring:
  datasource:
#    url: jdbc:oracle:thin:@192.168.1.98:1521:orcl
    driver: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fr_db/authority?useSSL=false&serverTimezone=UTC
    username: root
    password: root
