server:
  port: 8082
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
dubbo:
  registry:
    address: spring-cloud://localhost
  cloud:
    # The subscribed services in consumer side
    subscribed-services: dubbo-rest-provider

spring:
  http:
    encoding:
      charset: UTF-8
  application:
    name: dubbo-rest-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  main:
    allow-bean-definition-overriding: true